# Used Car Price Prediction
## 1. Problem Statement
- This dataset comprises used cars sold on cardekho.com in India as well as important features of these cars.
- If users can predict the price of the car based on input features.
- Prediction results can be used to give new seller the price suggestion based on market condition.

## 2. Data Collection
- The dataset is collected from scrapping from cardekho.com website.
- The data consists of 13 column and 15411 rows.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("cardekho_imputated.csv", index_col=0)
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Data Cleaning
### Handling Missing values
- Handling Missing values
- Handling Duplicates
- Check data type
- Understand the dataset

In [3]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

Remove unnecessary columns.

In [4]:
df.drop("car_name", axis=1, inplace=True)
df.drop("brand", axis=1, inplace=True)
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [5]:
df["model"].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

Indepedent and dependent features.

In [6]:
from sklearn.model_selection import train_test_split

X = df.drop(["selling_price"], axis=1)
y = df["selling_price"]

X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

## Feature Encoding and Scaling
One Hot Encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

In [7]:
len(df["model"].unique())

120

In [8]:
df["model"].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X["model"] = le.fit_transform(X["model"])

Create a column transformer with 3 types of transformers.

In [10]:
num_features = X.select_dtypes(exclude="object").columns
onehot_columns = ["seller_type", "fuel_type", "transmission_type"]

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop="first")

preprocessor = ColumnTransformer([
    ("OneHotEncoder", oh_transformer, onehot_columns),
    ("StandardScaler", numeric_transformer, num_features)
], remainder="passthrough")

In [11]:
X = preprocessor.fit_transform(X)
X

array([[ 1.        ,  0.        ,  0.        , ..., -1.32425883,
        -1.26335238, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43257082, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.47911321, -0.40302241],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  0.02291783,
         0.06822523, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  1.32979434,
         0.91715831,  2.07344426],
       [ 0.        ,  0.        ,  0.        , ...,  0.02099878,
         0.39588361, -0.40302241]], shape=(15411, 14))

Separate dataset into train and test.

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((12328, 14), (3083, 14))

## Model Training and Model Selection

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Create a function to evaluate the model

In [14]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2 = r2_score(true, predicted)
    return mae, mse, rmse, r2

Beginning Model Training.

In [15]:
models = {
    "Lienar Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor()
}

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    # Evaluate Train and Test dataset
    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])
    print("Model performance on Training set")
    print(f"MAE: {model_train_mae}")
    print(f"MSE: {model_train_mse}")
    print(f"RMSE: {model_train_rmse}")
    print(f"R2 Score: {model_train_r2}")
    
    print("------------------------------------------")

    print("Model performance on Test set")
    print(f"MAE: {model_test_mae}")
    print(f"MSE: {model_test_mse}")
    print(f"RMSE: {model_test_rmse}")
    print(f"R2 Score: {model_test_r2}")

    print("=" * 35)
    print("\n")

Lienar Regression
Model performance on Training set
MAE: 268101.6070829936
MSE: 306756099359.7596
RMSE: 553855.6665411663
R2 Score: 0.6217719576765959
------------------------------------------
Model performance on Test set
MAE: 279618.5794158427
MSE: 252550062888.56552
RMSE: 502543.59302309836
R2 Score: 0.6645109298852006
===================================


Lasso
Model performance on Training set
MAE: 268099.22264981153
MSE: 306756104248.3742
RMSE: 553855.6709544231
R2 Score: 0.6217719516489697
------------------------------------------
Model performance on Test set
MAE: 279614.74610341265
MSE: 252549134806.78134
RMSE: 502542.66963789385
R2 Score: 0.6645121627547996
===================================


Ridge
Model performance on Training set
MAE: 268059.8014688311
MSE: 306756818740.9266
RMSE: 553856.3159709624
R2 Score: 0.6217710706848424
------------------------------------------
Model performance on Test set
MAE: 279557.2168930274
MSE: 252540243247.96854
RMSE: 502533.8229890288
R2 Score: 0.6645239743566811
===================================


K-Neighbors Regressor
Model performance on Training set
MAE: 91425.63270603504
MSE: 106193229526.28163
RMSE: 325873.02669334516
R2 Score: 0.8690645193508602
------------------------------------------
Model performance on Test set
MAE: 112526.34609146934
MSE: 64021344520.150826
RMSE: 253024.39510875393
R2 Score: 0.9149536488136147
===================================


Decision Tree
Model performance on Training set
MAE: 5164.819922128488
MSE: 432524990.53644824
RMSE: 20797.23516567643
R2 Score: 0.9994666998284044
------------------------------------------
Model performance on Test set
MAE: 124344.70483295491
MSE: 88208349811.44359
RMSE: 296998.90540445363
R2 Score: 0.8828234809521325
===================================


Random Forest
Model performance on Training set
MAE: 39817.05486032597
MSE: 21966724877.86191
RMSE: 148211.7568813686
R2 Score: 0.9729151877855035
------------------------------------------
Model performance on Test set
MAE: 101129.30532182705
MSE: 52296540303.56219
RMSE: 228684.36829735912
R2 Score: 0.9305289514641512
===================================

We can play around with the *Hyperparameters* and retrain the models.