# Spam and Ham Project using Word2Vec and AvgWord2Vec
Importing and installing the required libraries.

In [1]:
! pip install gensim

import gensim
from gensim.models import Word2Vec, KeyedVectors

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 62.6 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

Loading the `Gensim` model.

In [2]:
import gensim.downloader as api

wv = api.load("word2vec-google-news-300")

vec_king = wv["king"]

[==================================================] 100.0% 1662.8/1662.8MB downloaded

Loading the dataset.

In [3]:
import pandas as pd
messages = pd.read_csv("/content/spam.csv")
messages.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1, inplace=True)
messages.rename({"v1":"label", "v2":"message"}, axis=1, inplace=True)
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

This time we will be using `Lemmatizer` instead of the `Stemmer`.

In [4]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [5]:
import re
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [6]:
corpus = []
for i in range(len(messages)):
  review = re.sub("[^a-zA-Z]", " ", messages["message"][i])
  review = review.lower()
  review = review.split()
  review = [lemmatizer.lemmatize(word) for word in review]
  review = " ".join(review)
  corpus.append(review)

In [7]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile update co free on',
 'i m gonna be home soon and i don t want to talk about this stuff anymore tonight k i ve cried enough today',
 'six chance to win cash from to pound txt csh and send to cost p day day tsandcs apply reply hl info',
 'urgent you have won a week free membership in our prize jackpot txt the word claim to no t c www dbuk net lccltd pobox ldnw a rw',
 'i ve been searching for the right word to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all time',
 'i have a date on sunday with will',
 'xxxmobilemovieclub to use your credit click the wap link in the next txt message or click here http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k i m watching here',
 'eh u remember how spell his name yes i did he v naughty make until i v wet',
 'fine if that s the way u feel that s the way it gota b',
 'england v macedonia dont miss the goal team news txt ur national team to eg england to try wale scotland txt poboxox w wq',
 'is that seriously how you spell his name',
 'i m going to try for month ha ha only joking',
 'so pay first lar then when is da stock comin',
 'aft i finish my lunch then i go str down lor ard smth lor u finish ur lunch already',
 'ffffffffff alright no way i can meet up with you sooner',
 'just forced myself to eat a slice i m really not hungry tho this suck mark is getting worried he know i m sick when i turn down pizza lol',
 'lol your always so convincing',
 'did you catch the bus are you frying an egg did you make a tea are you eating your mom s left over dinner do you feel my love',
 'i m back amp we re packing the car now i ll let you know if there s room',
 'ahhh work i vaguely remember that what doe it feel like lol',
 'wait that s still not all that clear were you not sure about me being sarcastic or that that s why x doesn t want to live with u',
 'yeah he got in at and wa v apologetic n had fallen out and she wa actin like spoilt child and he got caught up in that till but we won t go there not doing too badly cheer you',
 'k tell me anything about you',
 'for fear of fainting with the of all that housework you just did quick have a cuppa',
 'thanks for your subscription to ringtone uk your mobile will be charged month please confirm by replying yes or no if you reply no you will not be charged',
 'yup ok i go home look at the timing then i msg again xuhui going to learn on nd may too but her lesson is at am',
 'oops i ll let you know when my roommate s done',
 'i see the letter b on my car',
 'anything lor u decide',
 'hello how s you and how did saturday go i wa just texting to see if you d decided to do anything tomo not that i m trying to invite myself or anything',
 'pls go ahead with watt i just wanted to be sure do have a great weekend abiola',
 'did i forget to tell you i want you i need you i crave you but most of all i love you my sweet arabian steed mmmmmm yummy',
 'rodger burn msg we tried to call you re your reply to our sm for a free nokia mobile free camcorder please call now for delivery tomorrow',
 'who are you seeing',
 'great i hope you like your man well endowed i am lt gt inch',
 'no call message missed call',
 'didn t you get hep b immunisation in nigeria',
 'fair enough anything going on',
 'yeah hopefully if tyler can t do it i could maybe ask around a bit',
 'u don t know how stubborn i am i didn t even want to go to the hospital i kept telling mark i m not a weak sucker hospital are for weak sucker',
 'what you thinked about me first time you saw me in class',
 'a gram usually run like lt gt a half eighth is smarter though and get you almost a whole second gram for lt gt',
 'k fyi x ha a ride early tomorrow morning but he s crashing at our place tonight',
 'wow i never realized that you were so embarassed by your accomodations i thought you liked it since i wa doing the best i could and you always seemed so happy about the cave i m sorry i didn t and don t have more to give i m sorry i offered i m sorry your room wa so embarassing',
 'sm ac sptv the new jersey devil and the detroit red wing play ice hockey correct or incorrect end reply end sptv',
 'do you know what mallika sherawat did yesterday find out now lt url gt',
 'congrats year special cinema pas for is yours call now c suprman v matrix starwars etc all free bx ip we pm dont miss out',
 'sorry i ll call later in meeting',
 'tell where you reached',
 'yes gauti and sehwag out of odi series',
 'your gonna have to pick up a burger for yourself on your way home i can t even move pain is killing me',
 'ha ha ha good joke girl are situation seeker',
 'it a part of checking iq',
 'sorry my roommate took forever it ok if i come by now',
 'ok lar i double check wif da hair dresser already he said wun cut v short he said will cut until i look nice',
 'a a valued customer i am pleased to advise you that following recent review of your mob no you are awarded with a bonus prize call',
 'today is song dedicated day which song will u dedicate for me send this to all ur valuable frnds but first rply me',
 'urgent ur awarded a complimentary trip to eurodisinc trav aco entry or to claim txt dis to morefrmmob shracomorsglsuplt l aj',
 'did you hear about the new divorce barbie it come with all of ken s stuff',
 'i plane to give on this month end',
 'wah lucky man then can save money hee',
 'finished class where are you',
 'hi babe im at home now wanna do something xx',
 'k k where are you how did you performed',
 'u can call me now',
 'i am waiting machan call me once you free',
 'thats cool i am a gentleman and will treat you with dignity and respect',
 'i like you people very much but am very shy pa',
 'doe not operate after lt gt or what',
 'it not the same here still looking for a job how much do ta s earn there',
 'sorry i ll call later',
 'k did you call me just now ah',
 'ok i am on the way to home hi hi',
 'you will be in the place of that man',
 'yup next stop',
 'i call you later don t have network if urgnt sm me',
 'for real when u getting on yo i only need more ticket and one more jacket and i m done i already used all my multis',
 'yes i started to send request to make it but pain came back so i m back in bed double coin at the factory too i gotta cash in all my nitros',
 'i m really not up to it still tonight babe',
 'ela kano il download come wen ur free',
 'yeah do don t stand to close tho you ll catch something',
 'sorry to be a pain is it ok if we meet another night i spent late afternoon in casualty and that mean i haven t done any of y stuff moro and that includes all my time sheet and that sorry',
 'smile in pleasure smile in pain smile when trouble pours like rain smile when sum hurt u smile becoz someone still love to see u smiling',
 'please call our customer service representative on between am pm a you have won a guaranteed cash or prize',
 'havent planning to buy later i check already lido only got show in e afternoon u finish work already',
 'your free ringtone is waiting to be collected simply text the password mix to to verify get usher and britney fml',
 'watching telugu movie wat abt u',
 'i see when we finish we have load of loan to pay',
 'hi wk been ok on hols now yes on for a bit of a run forgot that i have hairdresser appointment at four so need to get home n shower beforehand doe that cause prob for u ham',
 'please don t text me anymore i have nothing else to say',
 'okay name ur price a long a it legal wen can i pick them up y u ave x am xx',
 'i m still looking for a car to buy and have not gone the driving test yet',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'wow you re right i didn t mean to do that i guess once i gave up on boston men and changed my search location to nyc something changed cuz on my signin page it still say boston',
 'umma my life and vava umma love you lot dear',
 'thanks a lot for your wish on my birthday thanks you for making my birthday truly memorable',
 'aight i ll hit you up when i get some cash',
 'how would my ip address test that considering my computer isn t a minecraft server',
 'i know grumpy old people my mom wa like you better not be lying then again i am always the one to play joke',
 'dont worry i guess he s busy',
 'what is the plural of the noun research',
 'going for dinner msg you after',
 'i m ok wif it co i like try new thing but i scared u dun like mah co u said not too loud',
 'gent we are trying to contact you last weekend draw show that you won a prize guaranteed call claim code k valid hr only ppm',
 'wa ur openin sentence very formal anyway i m fine too juz tt i m eatin too much n puttin on weight haha so anythin special happened',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'you are a winner u have been specially selected receive or a holiday flight inc speak to a live operator claim p min',
 'goodo yes we must speak friday egg potato ratio for tortilla needed',
 'hmm my uncle just informed me that he s paying the school directly so pls buy food',
 'private your account statement for show unredeemed bonus point to claim call identifier code expires',
 'urgent your mobile no wa awarded bonus caller prize on this is our final try to contact u call from landline box wr c ppm',
 'here is my new address apple pair all that malarky',
 'today voda number ending are selected to receive a award if you have a match please call quoting claim code standard rate app',
 'i am going to sao mu today will be done only at',
 'predict wat time ll finish buying',
 'good stuff will do',
 'just so that you know yetunde hasn t sent money yet i just sent her a text not to bother sending so it over you dont have to involve yourself in anything i shouldn t have imposed anything on you in the first place so for that i apologise',
 'are you there in room',
 'hey girl how r u hope u r well me an del r bak again long time no c give me a call sum time from lucyxx',
 'k k how much doe it cost',
 'i m home',
 'dear will call tmorrow pls accomodate',
 'first answer my question',
 'sunshine quiz wkly q win a top sony dvd player if u know which country the algarve is in txt ansr to sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join the uk s largest dogging network bt txting gravel to nt ec a p msg p',
 'i only haf msn it s yijue hotmail com',
 'he is there you call and meet him',
 'no no i will check all room befor activity',
 'you ll not rcv any more msg from the chat svc for free hardcore service text go to if u get nothing u must age verify with yr network try again',
 'got c i lazy to type i forgot in lect i saw a pouch but like not v nice',
 'k text me when you re on the way',
 'sir waiting for your mail',
 'a swt thought nver get tired of doing little thing lovable person coz somtimes those little thing occupy d biggest part in their heart gud ni',
 'i know you are can you pls open the back',
 'yes see ya not on the dot',
 'whats the staff name who is taking class for u',
 'freemsg why haven t you replied to my text i m randy sexy female and live local luv to hear from u netcollex ltd p per msg reply stop to end',
 'ummma will call after check in our life will begin from qatar so pls pray very hard',
 'k i deleted my contact that why',
 'sindu got job in birla soft',
 'the wine is flowing and i m i have nevering',
 'yup i thk cine is better co no need go down plaza mah',
 'ok ur typical reply',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'you are everywhere dirt on the floor the window even on my shirt and sometimes when i open my mouth you are all that come flowing out i dream of my world without you then half my chore are out too a time of joy for me lot of tv show i ll see but i guess like all thing you just must exist like rain hail and mist and when my time here is done you and i become one',
 'aaooooright are you at work',
 'i m leaving my house now',
 'hello my love what are you doing did you get to that interview today are you you happy are you being a good boy do you think of me are you missing me',
 'customer service annoncement you have a new year delivery waiting for you please call now to arrange delivery',
 'you are a winner u have been specially selected receive cash or a holiday flight inc speak to a live operator claim',
 'keep yourself safe for me because i need you and i miss you already and i envy everyone that see s you in real life',
 'new car and house for my parent i have only new job in hand',
 'i m so in love with you i m excited each day i spend with you you make me so happy',
 'pls stop bootydelious f is inviting you to be her friend reply yes or no see her www sm ac u bootydelious stop send stop frnd to',
 'bangbabes ur order is on the way u should receive a service msg download ur content if u do not goto wap bangb tv on ur mobile internet service menu',
 'i place all ur point on e culture module already',
 'urgent we are trying to contact you last weekend draw show that you have won a prize guaranteed call claim code s valid hr only',
 'hi frnd which is best way to avoid missunderstding wit our beloved one s',
 'great escape i fancy the bridge but need her lager see you tomo',
 'yes it completely in out of form clark also utter waste',
 'sir i need axis bank account no and bank address',
 'hmmm thk sure got time to hop ard ya can go free abt muz call u to discus liao',
 'what time you coming down later',
 'bloody hell cant believe you forgot my surname mr ill give u a clue it spanish and begin with m',
 'well i m gonna finish my bath now have a good fine night',
 'let me know when you ve got the money so carlos can make the call',
 'u still going to the mall',
 'turn out my friend are staying for the whole show and won t be back til lt gt so feel free to go ahead and smoke that lt gt worth',
 'text her if she doesnt reply let me know so i can have her log in',
 'hi you just spoke to maneesha v we d like to know if you were satisfied with the experience reply toll free with yes or no',
 'you lifted my hope with the offer of money i am in need especially when the end of the month approach and it hurt my studying anyways have a gr weekend',
 'lol no u can trust me',
 'ok i am a gentleman and will treat you with dignity and respect',
 'he will you guy close',
 'going on nothing great bye',
 'hello handsome are you finding that job not being lazy working towards getting back that net for mummy where s my boytoy now doe he miss me',
 'haha awesome be there in a minute',
 'please call our customer service representative on freephone between am pm a you have won a guaranteed cash or prize',
 'have you got xmas radio time if not i will get it now',
 'i jus reached home i go bathe first but my si using net tell u when she finish k',
 'are you unique enough find out from th august www areyouunique co uk',
 'i m sorry i ve joined the league of people that dont keep in touch you mean a great deal to me you have been a friend at all time even at great personal cost do have a great week',
 'hi finally i completed the course',
 'it will stop on itself i however suggest she stay with someone that will be able to give or for every stool',
 'how are you doing hope you ve settled in for the new school year just wishin you a gr day',
 'gud mrng dear hav a nice day',
 'did u got that person story',
 'is your hamster dead hey so tmr i meet you at pm orchard mrt',
 'hi it kate how is your evening i hope i can see you tomorrow for a bit but i have to bloody babyjontet txt back if u can xxx',
 'found it enc lt gt where you at',
 'i sent you lt gt buck',
 'hello darlin ive finished college now so txt me when u finish if u can love kate xxx',
 'your account ha been refilled successfully by inr lt decimal gt your keralacircle prepaid account balance is r lt decimal gt your transaction id is kr lt gt',
 'goodmorning sleeping ga',
 'u call me alter at ok',
 'say until like dat i dun buy ericsson oso cannot oredi lar',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'aight yo dat straight dogg',
 'you please give u connection today itself before lt decimal gt or refund the bill',
 'both i shoot big load so get ready',
 'what s up bruv hope you had a great break do have a rewarding semester',
 'home so we can always chat',
 'k k good study well',
 'yup how noe leh',
 'sound great are you home now',
 'finally the match heading towards draw a your prediction',
 'tired i haven t slept well the past few night',
 'easy ah sen got selected mean it good',
 'i have to take exam with march',
 'yeah you should i think you can use your gt atm now to register not sure but if there s anyway i can help let me know but when you do be sure you are ready',
 'ok no prob take ur time',
 'there is o called ubandu which will run without installing in hard disk you can use that o to copy the important file in system and give it to repair shop',
 'sorry i ll call later',
 'u say leh of course nothing happen lar not say v romantic jus a bit only lor i thk e nite scenery not so nice leh',
 'new mobile from must go txt nokia to no collect yours today from only www tc biz optout gbp mtmsg',
 'would really appreciate if you call me just need someone to talk to',
 'will u meet ur dream partner soon is ur career off a flyng start find out free txt horo followed by ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life is more strict than teacher bcoz teacher teach lesson amp then conduct exam but life first conduct exam amp then teach lesson happy morning',
 'dear good morning now only i am up',
 'get down in gandhipuram and walk to cross cut road right side lt gt street road and turn at first right',
 'dear we are going to our rubber place',
 'sorry battery died yeah i m here',
 'yes here tv is always available in work place',
 'text meet someone sexy today u can find a date or even flirt it up to u join just p reply with name age eg sam msg recd thirtyeight penny',
 'i have printed it oh so lt gt come upstairs',
 'or ill be a little closer like at the bus stop on the same street',
 'where are you when wil you reach here',
 'new theory argument win d situation but loses the person so dont argue with ur friend just kick them amp say i m always correct',
 'u have a secret admirer who is looking make contact with u find out who they r reveal who think ur so special call on',
 'tomarrow final hearing on my laptop case so i cant',
 'pleassssssseeeeee tel me v avent done sportsx',
 'okay no no just shining on that wa meant to be signing but that sound better',

In [8]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

We will be using `simple_preprocess` from the **Gensim** which pre-processes the given data using the pre-trained model.

In [9]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [10]:
words = []
for sent in corpus:
  sent_token = sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

Let's train this model.

In [11]:
import gensim

model = gensim.models.Word2Vec(sentences=words)

In [12]:
# Get the vocabulary size
model.corpus_count

5569

In [13]:
model.epochs

5

In [14]:
model.wv.similar_by_word("good")

[('hope', 0.9991095662117004),
 ('day', 0.9989493489265442),
 ('my', 0.9989069700241089),
 ('love', 0.9987552165985107),
 ('well', 0.998672604560852),
 ('great', 0.9986284375190735),
 ('did', 0.9986146092414856),
 ('dear', 0.9985958337783813),
 ('thing', 0.9985834956169128),
 ('much', 0.9985422492027283)]

In [15]:
model.wv["good"].shape

(100,)

In [16]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

Let's perform `AvgWord2Vec`. As we know that the `Word2Vec` can be memory consuming, to save that we will use average approach.

In [17]:
import numpy as np

def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv]
    if len(vectors) == 0:
        return np.zeros(model.vector_size)
    return np.mean(vectors, axis=0)

Import `tqdm` for progress bar.

In [18]:
from tqdm import tqdm

X = []
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

100%|██████████| 5569/5569 [00:00<00:00, 11438.36it/s]

In [19]:
X

[array([-0.20225409,  0.23711824,  0.16599862,  0.10830186,  0.12433972,
        -0.38227898,  0.24895176,  0.5421506 , -0.3263365 , -0.1206032 ,
        -0.15453084, -0.3716301 , -0.08131198,  0.06593578,  0.13240336,
        -0.13832374,  0.10952467, -0.3166413 ,  0.01471434, -0.51120776,
         0.1772449 ,  0.27758512,  0.07834803, -0.22112583, -0.06827475,
         0.07800665, -0.21564703, -0.17781426, -0.26705846,  0.04384015,
         0.20042707,  0.02864659,  0.16664378, -0.17506354, -0.06621345,
         0.3556177 , -0.03609397, -0.16897908, -0.14957613, -0.42834553,
         0.06724945, -0.22636193, -0.20813422, -0.04415166,  0.24245453,
        -0.05039973, -0.13497566, -0.12192474,  0.17772904,  0.16053315,
         0.13193159, -0.2407557 , -0.12299945, -0.01954261, -0.11019416,
         0.10825454,  0.09814119,  0.0188804 , -0.36699194,  0.15953523,
        -0.07062686,  0.07260083,  0.03681207, -0.12073113, -0.3345248 ,
         0.27857748,  0.16311914,  0.2893836 , -0.34749964,  0.25878033,
        -0.19505104,  0.1467793 ,  0.24608374, -0.19041999,  0.42243814,
         0.02932391,  0.02997002, -0.07907396, -0.19977728,  0.05486954,
        -0.13381483,  0.03354336, -0.22864516,  0.37432587, -0.07096801,
        -0.04193826,  0.08825795,  0.2624746 ,  0.412836  ,  0.09077027,
         0.29605195,  0.20262307,  0.12254245,  0.15591589,  0.45026243,
         0.26271927,  0.04527062, -0.22949873,  0.15277065, -0.06881652],
       dtype=float32),
 array([-0.18493524,  0.21056063,  0.14639515,  0.08737626,  0.11222637,
        -0.3369686 ,  0.21085417,  0.4765729 , -0.28635907, -0.10289682,
        -0.13614032, -0.3286781 , -0.06503525,  0.06788306,  0.12006776,
        -0.13032795,  0.10199996, -0.27806187,  0.00928775, -0.452432  ,
         0.15611416,  0.24947873,  0.06471089, -0.19471729, -0.05643564,
         0.06534086, -0.18980797, -0.15686506, -0.23833312,  0.04379676,
         0.17281382,  0.02753249,  0.14032811, -0.157163  , -0.06304705,
         0.30957615, -0.03840581, -0.14996108, -0.12318417, -0.38633955,
         0.06315552, -0.20122397, -0.17523289, -0.04273318,  0.21248454,
        -0.04618103, -0.11039539, -0.11897146,  0.15732455,  0.14666626,
         0.10958728, -0.20605499, -0.10963936, -0.01317078, -0.09629738,
         0.09343536,  0.08751395,  0.01699699, -0.3244304 ,  0.14085121,
        -0.05809373,  0.0635271 ,  0.02382392, -0.09991429, -0.2972398 ,
         0.24155813,  0.14690764,  0.24828567, -0.30902818,  0.23587632,
        -0.16862278,  0.1251688 ,  0.22176248, -0.16349274,  0.36997017,
         0.01615852,  0.02844726, -0.06815358, -0.18027256,  0.04174092,
        -0.1104591 ,  0.03602558, -0.20672974,  0.32838392, -0.06614183,
        -0.03409379,  0.07678534,  0.23895237,  0.35267815,  0.08540937,
         0.26150334,  0.17076293,  0.10445908,  0.13684721,  0.3892783 ,
         0.23507121,  0.04016997, -0.20496479,  0.12880877, -0.06307355],
       dtype=float32),
 array([-0.20235886,  0.24871379,  0.18003751,  0.13285309,  0.13261557,
        -0.4188372 ,  0.24027668,  0.5461905 , -0.34925392, -0.10971402,
        -0.19174014, -0.4098852 , -0.07571822,  0.05409882,  0.16602625,
        -0.11263041,  0.11714477, -0.34325454,  0.01325478, -0.53391594,
         0.16553646,  0.32008246,  0.06084174, -0.2278171 , -0.07030232,
         0.13204761, -0.23521052, -0.1323178 , -0.26922652,  0.07017985,
         0.20848523,  0.04163312,  0.17522132, -0.14086786, -0.07347348,
         0.41972816, -0.02545015, -0.17643367, -0.15634991, -0.4565965 ,
         0.0813776 , -0.27606097, -0.23617998, -0.06260278,  0.24227686,
        -0.03339946, -0.1741054 , -0.12265289,  0.16103156,  0.12243864,
         0.12271583, -0.28981185, -0.12250627, -0.00482028, -0.15071301,
         0.14099254,  0.09955175,  0.00349271, -0.3682307 ,  0.17641683,
        -0.07971632,  0.08450541,  0.06159269, -0.12037969, -0.34047252,
         0.32682848,  0.17298265,  0.30926734, -0.35702857,  0.26370683,
        -0.2188585 ,  0.13408194,  0.26309755, -0.20798583,  0.4177311 ,
         0.04079277,  0.00140364, -0.07512207, -0.17748445,  0.05253666,
        -0.13325448,  0.01092729, -0.23441876,  0.3676614 , -0.05638085,
        -0.04161302,  0.05025106,  0.26489884,  0.4599412 ,  0.08009586,
         0.32616094,  0.20207344,  0.11707438,  0.15695168,  0.45909053,
         0.25560924,  0.0429661 , -0.25305498,  0.165158  , -0.05973984],
       dtype=float32),
 array([-0.2800209 ,  0.32837853,  0.22341703,  0.14134656,  0.16599749,
        -0.5209378 ,  0.33972448,  0.7388924 , -0.45023322, -0.17026746,
        -0.20509304, -0.5033492 , -0.10241752,  0.10479607,  0.17408107,
        -0.2014022 ,  0.1600212 , -0.4231451 ,  0.02099565, -0.7058682 ,
         0.24262609,  0.36836666,  0.11531495, -0.30079123, -0.08995762,
         0.09407307, -0.30031714, -0.25856957, -0.3657559 ,  0.05615456,
         0.26567262,  0.03771475,  0.21764652, -0.2508767 , -0.09515084,
         0.47253683, -0.05972277, -0.23361373, -0.19684847, -0.5800207 ,
         0.09977991, -0.29830703, -0.2704051 , -0.05314939,  0.33273458,
        -0.07120253, -0.16812646, -0.18068537,  0.24782348,  0.22662213,
         0.17053866, -0.3118686 , -0.16221778, -0.03067265, -0.12756275,
         0.14043762,  0.13605188,  0.038274  , -0.4958454 ,  0.21924482,
        -0.08341026,  0.09682649,  0.03635697, -0.15075333, -0.45546934,
         0.37535432,  0.22250302,  0.38299772, -0.47145182,  0.36089867,
        -0.2625639 ,  0.19567084,  0.3396647 , -0.25394887,  0.57836723,
         0.0366319 ,  0.04290917, -0.1058658 , -0.28345686,  0.06374341,
        -0.18219769,  0.05602884, -0.31635216,  0.5109254 , -0.10210742,
        -0.05207899,  0.14484806,  0.3592846 ,  0.5456478 ,  0.11581272,
         0.39212817,  0.2632114 ,  0.15851547,  0.22016582,  0.6061543 ,
         0.36075288,  0.06535285, -0.31856295,  0.1990248 , -0.08871049],
       dtype=float32),
 array([-0.24366331,  0.26772776,  0.1935312 ,  0.11284569,  0.14793679,
        -0.43635663,  0.28076676,  0.6199159 , -0.3724321 , -0.15387587,
        -0.16333205, -0.42767027, -0.08948275,  0.07756765,  0.1468071 ,
        -0.17201762,  0.14223464, -0.36293817,  0.01789259, -0.5907657 ,
         0.20810585,  0.30693224,  0.09651124, -0.24999356, -0.06562109,
         0.07917202, -0.25185066, -0.2094357 , -0.3047582 ,  0.0411796 ,
         0.22892655,  0.03359845,  0.18731655, -0.21620606, -0.07997282,
         0.39302674, -0.0416759 , -0.19581844, -0.15824051, -0.48607376,
         0.08861902, -0.26148084, -0.23136137, -0.04211346,  0.27679342,
        -0.05357467, -0.14752705, -0.14519063,  0.19692929,  0.19422364,
         0.15002882, -0.2645483 , -0.13395631, -0.0198219 , -0.10810607,
         0.11948665,  0.11255613,  0.03171173, -0.4211931 ,  0.19346488,
        -0.0716769 ,  0.0842061 ,  0.03754945, -0.13124757, -0.37960878,
         0.31732658,  0.19459023,  0.3258781 , -0.3876579 ,  0.30286577,
        -0.22661728,  0.16484569,  0.28369272, -0.20586081,  0.4842678 ,
         0.02773741,  0.02411343, -0.0864146 , -0.23788597,  0.04708774,
        -0.15669395,  0.05346563, -0.26264986,  0.43399695, -0.07804857,
        -0.03141924,  0.13489948,  0.29240602,  0.4595935 ,  0.09508595,
         0.33808485,  0.21761537,  0.13715191,  0.1855423 ,  0.5126473 ,
         0.30960473,  0.04682913, -0.27243987,  0.16917263, -0.07623334],
       dtype=float32),
 array([-0.24799387,  0.2865961 ,  0.20405671,  0.12900513,  0.15735094,
        -0.47550982,  0.2950832 ,  0.6573455 , -0.4026822 , -0.15639982,
        -0.18523961, -0.4645163 , -0.09293073,  0.0815445 ,  0.1636098 ,
        -0.16305941,  0.1463235 , -0.3854208 ,  0.01888165, -0.62897164,
         0.21222842,  0.33508232,  0.09833004, -0.26847708, -0.07426339,
         0.10351402, -0.26331276, -0.20174472, -0.32266387,  0.05385934,
         0.24461494,  0.0379327 ,  0.20714547, -0.21553972, -0.08478318,
         0.43854108, -0.03781729, -0.20857428, -0.17631951, -0.5225245 ,
         0.08694124, -0.2881555 , -0.25613332, -0.05485167,  0.29656065,
        -0.05463146, -0.1713157 , -0.1499245 ,  0.20688562,  0.18733884,
         0.15843622, -0.29271415, -0.14378513, -0.01855064, -0.13012087,
         0.13428429,  0.11625195,  0.02282102, -0.44156483,  0.20090212,
        -0.08191007,  0.09171454,  0.04879556, -0.13820994, -0.40425986,
         0.35102004,  0.19940805,  0.35266036, -0.41798228,  0.31810632,
        -0.24486943,  0.17374952,  0.29840255, -0.22568819,  0.5104192 ,
         0.0364444 ,  0.02187861, -0.09099664, -0.23761101,  0.05459935,
        -0.1649495 ,  0.04073288, -0.2777147 ,  0.45192248, -0.08141861,
        -0.04250694,  0.11896059,  0.309922  ,  0.50196004,  0.10179391,
         0.36372474,  0.23683532,  0.14548014,  0.19195126,  0.54611903,
         0.32167637,  0.05196197, -0.28674203,  0.18717967, -0.07660035],
       dtype=float32),
 array([-0.26258594,  0.30293116,  0.22170363,  0.13325076,  0.16859044,
        -0.49851683,  0.3177378 ,  0.70430577, -0.42772862, -0.16769317,
        -0.18772277, -0.48895898, -0.09446786,  0.09142657,  0.16857418,
        -0.18310343,  0.15703154, -0.40510032,  0.01902998, -0.6744565 ,
         0.23011221,  0.34804073,  0.11111103, -0.2900663 , -0.08049893,
         0.09511799, -0.28612882, -0.23015563, -0.34388202,  0.05143512,
         0.25822985,  0.03901314,  0.22268546, -0.24538653, -0.08953585,
         0.45981786, -0.05163362, -0.2261715 , -0.19235499, -0.5545224 ,
         0.09539886, -0.3002619 , -0.26270592, -0.05109519,  0.32365495,
        -0.06602458, -0.17310417, -0.16405609,  0.22668059,  0.21076028,
         0.16924748, -0.30228302, -0.15811987, -0.02366657, -0.1303484 ,
         0.13705985,  0.12154985,  0.03115976, -0.47213194,  0.20910944,
        -0.08600734,  0.09746069,  0.04363563, -0.14289163, -0.4312993 ,
         0.37003645,  0.21529238,  0.3764341 , -0.4488502 ,  0.33821303,
        -0.25829944,  0.19270296,  0.31940672, -0.23529704,  0.5529636 ,
         0.03561826,  0.03097642, -0.10563461, -0.26290438,  0.06443056,
        -0.1827054 ,  0.047614  , -0.2981112 ,  0.49081394, -0.09096432,
        -0.04474194,  0.13941129,  0.3309161 ,  0.5299202 ,  0.11404412,
         0.3805973 ,  0.25007743,  0.15609756,  0.20629406,  0.5840069 ,
         0.347945  ,  0.0567585 , -0.3018517 ,  0.19280592, -0.08950024],
       dtype=float32),
 array([-0.18850824,  0.23200251,  0.17484897,  0.11810039,  0.12422208,
        -0.38964844,  0.23832849,  0.52644366, -0.3293944 , -0.11216982,
        -0.16606975, -0.38864788, -0.06615847,  0.06151809,  0.14187919,
        -0.11573151,  0.10612092, -0.32102436,  0.01513132, -0.5085509 ,
         0.16927516,  0.2924737 ,  0.06872074, -0.21947317, -0.07132715,
         0.10135567, -0.21085152, -0.15064207, -0.257839  ,  0.04318942,
         0.19809662,  0.03643731,  0.17933278, -0.14989218, -0.07391666,
         0.3779559 , -0.02877568, -0.16874027, -0.15635337, -0.4279595 ,
         0.06460667, -0.25085932, -0.21706982, -0.05696988,  0.23867622,
        -0.03860193, -0.15745954, -0.11938337,  0.16700912,  0.14174679,
         0.13003202, -0.24661376, -0.12879573, -0.0202454 , -0.12104621,
         0.11799462,  0.08647924,  0.01554406, -0.35647258,  0.1570662 ,
        -0.08675092,  0.07970179,  0.05442332, -0.11900804, -0.3314237 ,
         0.2980156 ,  0.15619092,  0.28935474, -0.3447573 ,  0.24910949,
        -0.19583473,  0.14014108,  0.24112199, -0.19414167,  0.4242002 ,
         0.03910278,  0.02492543, -0.08558413, -0.17801169,  0.05958259,
        -0.13173388,  0.02189726, -0.22349346,  0.3625981 , -0.06421027,
        -0.04576563,  0.06538301,  0.24919513,  0.43222025,  0.08480675,
         0.29470032,  0.205229  ,  0.12463649,  0.15339892,  0.44032076,
         0.25761336,  0.04499252, -0.2307568 ,  0.16897374, -0.06694791],
       dtype=float32),
 array([-0.21817699,  0.26979306,  0.20449209,  0.13979632,  0.1424675 ,
        -0.4432492 ,  0.27408272,  0.6030024 , -0.3757989 , -0.12744842,
        -0.19894068, -0.44310173, -0.07760701,  0.06325378,  0.18367   ,
        -0.12493299,  0.12337238, -0.36846402,  0.01166692, -0.5695325 ,
         0.19713815,  0.3348286 ,  0.06635004, -0.25802603, -0.08474097,
         0.13015501, -0.24811557, -0.16125512, -0.28723836,  0.05976745,
         0.21753491,  0.0332928 ,  0.19395125, -0.14483167, -0.08755103,
         0.43129268, -0.02369798, -0.17163248, -0.16753507, -0.48844358,
         0.0872913 , -0.28631723, -0.25991234, -0.05520825,  0.26066223,
        -0.0391477 , -0.1943773 , -0.12760691,  0.18567994,  0.153012  ,
         0.1448296 , -0.30397978, -0.13374947, -0.0044212 , -0.15305229,
         0.15625176,  0.11113646,  0.01573553, -0.3952041 ,  0.1892568 ,
        -0.10041975,  0.08766568,  0.07925421, -0.1361454 , -0.3685499 ,
         0.34658393,  0.1854934 ,  0.32736674, -0.38400924,  0.2883248 ,
        -0.23161969,  0.1449652 ,  0.27056795, -0.23754351,  0.45302773,
         0.03915695,  0.01086259, -0.08402888, -0.18826832,  0.07180938,
        -0.13931958,  0.02203798, -0.2514347 ,  0.38857847, -0.05420911,
        -0.04912611,  0.05788136,  0.28242597,  0.4935489 ,  0.08331567,
         0.34384704,  0.21909729,  0.13388143,  0.16224124,  0.49717084,
         0.27387208,  0.03623018, -0.2775387 ,  0.18829292, -0.06193309],
       dtype=float32),
 array([-0.2504305 ,  0.31096745,  0.2318009 ,  0.17111228,  0.16292652,
        -0.52530336,  0.30275866,  0.6806013 , -0.4311695 , -0.12852201,
        -0.25223735, -0.51994   , -0.0884313 ,  0.06450118,  0.21627235,
        -0.13465439,  0.13643178, -0.43835527,  0.02006052, -0.6681501 ,
         0.20055957,  0.40932232,  0.0740198 , -0.29039037, -0.09062295,
         0.16362672, -0.29215539, -0.15577143, -0.3330468 ,  0.08277608,
         0.26037568,  0.05385708,  0.22801714, -0.16014901, -0.10576145,
         0.53603727, -0.03354518, -0.22192687, -0.19941711, -0.57181364,
         0.09257711, -0.35720217, -0.29939365, -0.08437599,  0.30220532,
        -0.03268502, -0.22497396, -0.15576282,  0.19916178,  0.15404327,
         0.15702981, -0.362616  , -0.16078064, -0.01712   , -0.1923613 ,
         0.18298204,  0.11231042, -0.00367517, -0.46286547,  0.21718329,
        -0.10859221,  0.10507815,  0.0905022 , -0.15402874, -0.42688534,
         0.4150585 ,  0.20866992,  0.39222106, -0.45256326,  0.3349135 ,
        -0.26387176,  0.17527552,  0.32228965, -0.2708672 ,  0.5330148 ,
         0.06138691,  0.00990369, -0.10610028, -0.20982304,  0.07666257,
        -0.1701069 ,  0.00474386, -0.29272017,  0.46767765, -0.06761035,
        -0.05974546,  0.04494679,  0.32748136,  0.5860361 ,  0.10322782,
         0.4080785 ,  0.26076886,  0.15286086,  0.18697062,  0.5764955 ,
         0.32373726,  0.05551725, -0.31711093,  0.2190386 , -0.07899433],
       dtype=float32),
 array([-0.25316644,  0.2804271 ,  0.19895552,  0.11558247,  0.15572087,
        -0.46143964,  0.28846115,  0.6489768 , -0.38962477, -0.15579246,
        -0.17055579, -0.45063853, -0.0888106 ,  0.07861894,  0.15647265,
        -0.17400242,  0.14879139, -0.3799772 ,  0.0150561 , -0.61786354,
         0.21313988,  0.32237402,  0.10029668, -0.26465902, -0.07106885,
         0.08686423, -0.25956196, -0.21170339, -0.31605285,  0.04652743,
         0.24022274,  0.03522107,  0.19933678, -0.21437044, -0.08592088,
         0.41585922, -0.04115131, -0.20912926, -0.16699958, -0.5101724 ,
         0.08871455, -0.27771103, -0.24427739, -0.0476613 ,  0.290428  ,
        -0.05258351, -0.15923926, -0.15101676,  0.20552264,  0.19190294,
         0.15708233, -0.28032038, -0.1402111 , -0.0176311 , -0.11545677,
         0.12916362,  0.11949462,  0.03089176, -0.43245387,  0.19834101,
        -0.074719  ,  0.09032676,  0.04371946, -0.13421601, -0.39601815,
         0.33867648,  0.19744287,  0.34359598, -0.4089684 ,  0.3115142 ,
        -0.23975249,  0.1700007 ,  0.29413393, -0.2167257 ,  0.50252956,
         0.03231218,  0.02173765, -0.0895971 , -0.24268796,  0.05341944,
        -0.16293335,  0.04879933, -0.27069503,  0.4471883 , -0.07844131,
        -0.03807025,  0.13064414,  0.30009568,  0.4819378 ,  0.09736653,
         0.35794955,  0.22961904,  0.14202464,  0.1872273 ,  0.5380911 ,
         0.31937182,  0.04893483, -0.2836748 ,  0.18122615, -0.07561064],
       dtype=float32),
 array([-0.24482451,  0.2953392 ,  0.21477588,  0.15640838,  0.16653936,
        -0.5047019 ,  0.2906423 ,  0.6572008 , -0.4166643 , -0.13132177,
        -0.21835369, -0.48936716, -0.0916795 ,  0.06693272,  0.19714983,
        -0.13884778,  0.14550059, -0.40885538,  0.01407386, -0.6396077 ,
         0.20379917,  0.3712705 ,  0.07710615, -0.27372175, -0.08196276,
         0.14805643, -0.276601  , -0.16292553, -0.3219639 ,  0.07684425,
         0.25295848,  0.0416941 ,  0.21196057, -0.16986145, -0.0894523 ,
         0.4909347 , -0.02547129, -0.2121707 , -0.18605503, -0.541867  ,
         0.10100776, -0.32762182, -0.28077975, -0.06754228,  0.28685108,
        -0.03820202, -0.20893137, -0.14421444,  0.19153805,  0.1559264 ,
         0.15155451, -0.34338546, -0.1405396 , -0.0077234 , -0.17629936,
         0.16447678,  0.12001862,  0.01223378, -0.43641105,  0.21512562,
        -0.09458932,  0.0972995 ,  0.07234196, -0.14253628, -0.4033808 ,
         0.38735002,  0.20842855,  0.36999604, -0.42861244,  0.3202294 ,
        -0.2628054 ,  0.16018783,  0.30903286, -0.24720223,  0.5023668 ,
         0.04094189,  0.00634624, -0.09217867, -0.21495548,  0.06156291,
        -0.16156478,  0.02018661, -0.27649453,  0.44133973, -0.06570432,
        -0.0444465 ,  0.0712751 ,  0.30972576,  0.54395604,  0.09106216,
         0.38382477,  0.24171199,  0.14040715,  0.18500473,  0.5497392 ,
         0.3065291 ,  0.05401829, -0.30908895,  0.19943279, -0.07446554],
       dtype=float32),
 array([-0.26057982,  0.31194735,  0.23093525,  0.16148786,  0.16630378,
        -0.5191121 ,  0.3107394 ,  0.68932515, -0.4364758 , -0.14321816,
        -0.23069806, -0.5120738 , -0.09148422,  0.0619371 ,  0.20781179,
        -0.1443434 ,  0.14735381, -0.43455797,  0.01688236, -0.6722523 ,
         0.21523967,  0.39749852,  0.07871377, -0.29070655, -0.08994439,
         0.15618701, -0.28971803, -0.17461699, -0.33088085,  0.07209928,
         0.25742674,  0.04295439,  0.22222248, -0.17361538, -0.09944277,
         0.508348  , -0.02997013, -0.21503173, -0.19029689, -0.5738635 ,
         0.10253613, -0.33862692, -0.29942515, -0.06887331,  0.3025762 ,
        -0.04503277, -0.22438316, -0.15001814,  0.20316076,  0.16656189,
         0.16179636, -0.35707387, -0.15297392, -0.00592353, -0.18153472,
         0.17736532,  0.12475573,  0.01005998, -0.46269074,  0.21959126,
        -0.10463466,  0.1000025 ,  0.09128134, -0.15214728, -0.4296087 ,
         0.4043793 ,  0.21399358,  0.38598093, -0.44780093,  0.3329399 ,
        -0.27016866,  0.17595302,  0.31981042, -0.27111882,  0.5297792 ,
         0.0448524 ,  0.01133436, -0.09569903, -0.2262077 ,  0.07503939,
        -0.159856  ,  0.0173335 , -0.28621632,  0.46287125, -0.06429032,
        -0.04791451,  0.07157033,  0.3277445 ,  0.5716359 ,  0.09680805,
         0.3993126 ,  0.25789574,  0.15199676,  0.19578242,  0.5826328 ,
         0.324191  ,  0.05009935, -0.32383442,  0.22093125, -0.0717603 ],
       dtype=float32),
 array([-0.25091365,  0.2831846 ,  0.20491849,  0.1236124 ,  0.15630855,
        -0.47350553,  0.29892722,  0.65964144, -0.3975895 , -0.15792   ,
        -0.17643695, -0.46407434, -0.08603825,  0.07462884,  0.15929408,
        -0.16701013,  0.14875329, -0.39027017,  0.0183081 , -0.6290761 ,
         0.21589932,  0.3348152 ,  0.10014118, -0.26803696, -0.07454321,
         0.09583365, -0.25866914, -0.20707117, -0.3216494 ,  0.04227997,
         0.24346079,  0.03717295,  0.21097173, -0.21207668, -0.08913221,
         0.43168685, -0.03811193, -0.2136467 , -0.1756772 , -0.51896137,
         0.08438165, -0.2848293 , -0.25233862, -0.04963229,  0.2961847 ,

Here, we have completed the `AvgWord2Vec`.<br>
Now, we will consider the above as the *Independent Feature*.

In [20]:
X_new = np.array(X)
X_new.shape

(5569, 100)

In [21]:
X_new[0]

array([-0.20225409,  0.23711824,  0.16599862,  0.10830186,  0.12433972,
       -0.38227898,  0.24895176,  0.54215062, -0.3263365 , -0.1206032 ,
       -0.15453084, -0.3716301 , -0.08131198,  0.06593578,  0.13240336,
       -0.13832374,  0.10952467, -0.3166413 ,  0.01471434, -0.51120776,
        0.1772449 ,  0.27758512,  0.07834803, -0.22112583, -0.06827475,
        0.07800665, -0.21564703, -0.17781426, -0.26705846,  0.04384015,
        0.20042707,  0.02864659,  0.16664378, -0.17506354, -0.06621345,
        0.3556177 , -0.03609397, -0.16897908, -0.14957613, -0.42834553,
        0.06724945, -0.22636193, -0.20813422, -0.04415166,  0.24245453,
       -0.05039973, -0.13497566, -0.12192474,  0.17772904,  0.16053315,
        0.13193159, -0.24075571, -0.12299945, -0.01954261, -0.11019416,
        0.10825454,  0.09814119,  0.0188804 , -0.36699194,  0.15953523,
       -0.07062686,  0.07260083,  0.03681207, -0.12073113, -0.33452481,
        0.27857748,  0.16311914,  0.28938359, -0.34749964,  0.25878033,
       -0.19505104,  0.1467793 ,  0.24608374, -0.19041999,  0.42243814,
        0.02932391,  0.02997002, -0.07907396, -0.19977728,  0.05486954,
       -0.13381483,  0.03354336, -0.22864516,  0.37432587, -0.07096801,
       -0.04193826,  0.08825795,  0.2624746 ,  0.41283599,  0.09077027,
        0.29605195,  0.20262307,  0.12254245,  0.15591589,  0.45026243,
        0.26271927,  0.04527062, -0.22949873,  0.15277065, -0.06881652])

Let's go for the *Dependent Feature*.

In [22]:
y = pd.get_dummies(messages["label"])
y = y.iloc[:, 0:].values

In [23]:
messages.shape

(5572, 2)

If we take a look closely, we will observe that the number of records in `messages` is 3 more than that of `X`. Where are these 3 records?<br>
Basically, during the pre-processing only the sentences containing A-B and a-z. So the messages which doesn't contain these are deleted.

In [24]:
y = messages[list(map(lambda x : len(x) > 0, corpus))]
y = pd.get_dummies(y["label"])
y = y.iloc[:,0].values
y.shape

(5569,)

Let's go for finalizing the *Independent Features*. Let's create a DataFrame for storing the vector of each sentence in a single row.

In [25]:
X[0].reshape(1, -1).shape

(1, 100)

In [28]:
rows = []
for i in range(len(X)):
    rows.append(X[i].reshape(1, -1))

df = pd.concat([pd.DataFrame(r) for r in rows], ignore_index=True)

df.shape

(5569, 100)

In [29]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.202254,0.237118,0.165999,0.108302,0.124340,-0.382279,0.248952,0.542151,-0.326337,-0.120603,...,0.296052,0.202623,0.122542,0.155916,0.450262,0.262719,0.045271,-0.229499,0.152771,-0.068817
1,-0.184935,0.210561,0.146395,0.087376,0.112226,-0.336969,0.210854,0.476573,-0.286359,-0.102897,...,0.261503,0.170763,0.104459,0.136847,0.389278,0.235071,0.040170,-0.204965,0.128809,-0.063074
2,-0.202359,0.248714,0.180038,0.132853,0.132616,-0.418837,0.240277,0.546191,-0.349254,-0.109714,...,0.326161,0.202073,0.117074,0.156952,0.459091,0.255609,0.042966,-0.253055,0.165158,-0.059740
3,-0.280021,0.328379,0.223417,0.141347,0.165997,-0.520938,0.339724,0.738892,-0.450233,-0.170267,...,0.392128,0.263211,0.158515,0.220166,0.606154,0.360753,0.065353,-0.318563,0.199025,-0.088710
4,-0.243663,0.267728,0.193531,0.112846,0.147937,-0.436357,0.280767,0.619916,-0.372432,-0.153876,...,0.338085,0.217615,0.137152,0.185542,0.512647,0.309605,0.046829,-0.272440,0.169173,-0.076233

Independent Feature

In [30]:
X = df

Train Test Split

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [32]:
X_train.head(5)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
2675,-0.254785,0.319243,0.231828,0.149861,0.159072,-0.510431,0.338271,0.721824,-0.436229,-0.152367,...,0.399758,0.270471,0.167002,0.209424,0.599239,0.346209,0.063055,-0.292766,0.202293,-0.088375
3591,-0.250605,0.312401,0.231500,0.168074,0.165857,-0.538592,0.304988,0.697609,-0.437043,-0.142538,...,0.420152,0.257395,0.147930,0.193788,0.589244,0.329004,0.049625,-0.327439,0.211608,-0.076424
270,-0.249944,0.276567,0.200232,0.127255,0.156152,-0.460625,0.279362,0.639958,-0.393030,-0.143931,...,0.359753,0.226764,0.132445,0.184204,0.526540,0.307594,0.041622,-0.289425,0.186560,-0.064772
215,-0.190448,0.224063,0.159138,0.097913,0.122793,-0.362108,0.219680,0.496578,-0.310222,-0.105723,...,0.281000,0.184569,0.113256,0.144000,0.415063,0.242290,0.044717,-0.225897,0.159033,-0.061930
823,-0.206759,0.246619,0.179282,0.128386,0.132121,-0.414013,0.242969,0.553502,-0.354803,-0.111358,...,0.318234,0.210055,0.123960,0.161415,0.467433,0.264324,0.049141,-0.250339,0.165226,-0.064934

In [33]:
y

array([ True,  True, False, ...,  True,  True,  True])

Now, we are ready to apply any machine learning algorithm over this.

In [35]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [36]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

Sometimes, a problem might arise that there are some `NaN` values. To solve that, we need to remove them from the dataset simply.<br>
Let's predict.

In [37]:
y_pred = classifier.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(y_test, y_pred))

0.9766606822262118

In [39]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.92      0.91      0.91       148
        True       0.99      0.99      0.99       966

    accuracy                           0.98      1114
   macro avg       0.95      0.95      0.95      1114
weighted avg       0.98      0.98      0.98      1114